name: 'Load environment'
description: 'Loads organization specific environment variables'
outputs:
  gh-org:
    description: "GitHub Organization"
    value: ${{ steps.load-env.outputs.gh-org }}
  mvn-releases-url:
    description: "Maven Releases URL"
    value: ${{ steps.load-env.outputs.mvn-releases-url }}
  mvn-snapshots-url:
    description: "Maven Snapshots URL"
    value: ${{ steps.load-env.outputs.mvn-snapshots-url }}
  quay-org:
    description: "Quay Organization"
    value: ${{ steps.load-env.outputs.quay-org }}

runs:
  steps:
    - use: actions/checkout@v3
    - id: load-env
      run: cat .github/env/${{ github.repository_owner }} | grep '=' | sed 's/=/::/g' | xargs -I {} echo "::set-output name={}"
      shell: bash
