name: Report flaky test
description: Finds flaky tests and creates issues

runs:
  using: composite
  steps:
    - id: flaky-tests
      name: Find flaky tests
      if: github.repository == 'stianst/playground'
      shell: bash
      run: |
        REPO="${{ github.repository }}"
        ISSUES_LINK="https://github.com/${{ github.repository }}/issues/"
        PR="${{ github.event.pull_request.number }}"
        RUN="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        
        FLAKES=""
        SEP=""
        for dir in $(find -type d -name surefire-reports); do
          for i in $(grep -l '<flakyFailure' $dir/TEST-*.xml); do
          FLAKES="$FLAKES$SEP$i"
          SEP=$'\n'
          done
        done
        
        if [ "$FLAKES" != "" ]; then
          echo "flakes<<EOF" >> $GITHUB_OUTPUT
          echo "$FLAKES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - uses: actions/upload-artifact@v3
      with:
        name: flaky-tests
        path: ${{ steps.flaky-tests.flakes }}
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`