name: Report flaky test
description: Finds flaky tests and creates issues

runs:
  using: composite
  steps:
    - id: flaky-tests
      name: Find flaky tests
      if: github.repository == 'stianst/playground'
      shell: bash
      run: |
        echo 'Checking for flakes'
        
        for dir in `find -type d -name surefire-reports`; do
          for i in `ls $dir/*.txt`; do
            if ( grep '<<< FAILURE!' $i &>/dev/null ); then
              TEST="`echo $i | sed 's/.txt//g' | sed 's/.*\.//g'`"
              LOG="`cat $i`"
              
              RUN="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              TITLE="Flaky test: $TEST"
              BODY="$RUN"$'\n'"\`\`\`"$'\n'"$LOG"$'\n'"\`\`\`"
              ISSUE="`gh issue list --search "$TITLE in:title" --json number --jq .[].number`"
              ISSUES_LINK="https://github.com/${{ github.repository }}/issues/"
        
              if [ "$ISSUE" == "" ]; then
                ISSUE=`gh issue create -t "$TITLE" -b "$BODY" -l "kind/bug,area/ci,flaky-test" | grep $ISSUES_LINK | sed "s|$ISSUES_LINK||"
              else
                gh issue comment "$ISSUE" -b "$BODY" >> $GITHUB_STEP_SUMMARY
              fi    

              gh api -X POST "repos/${{ github.repository }}/issues/$ISSUE/reactions" --input - <<< '{"content":"+1"}'
        
              PR="${{ github.event.pull_request.number }}"
              if [ "$PR" != "" ]; then
                gh pr edit "$PR" --add-label "flaky-test"
              fi
              
              echo "## $TITLE" >> $GITHUB_STEP_SUMMARY
              echo "$ISSUES_LINK/$ISSUE" >> $GITHUB_STEP_SUMMARY
              echo "```" >> $GITHUB_STEP_SUMMARY
              echo "$LOG" >> $GITHUB_STEP_SUMMARY
              echo "```" >> $GITHUB_STEP_SUMMARY
            fi
          done
        done
