
name: Test

on:

  push:

jobs:
  one:
    runs-on: ubuntu-latest
    if: 1 == 1
    steps:
      - uses: actions/checkout@v3

      - id: one
        run: |
          echo "one"
  two:
    runs-on: ubuntu-latest
    env:
      KEY: ${{ secrets.TEST }}
    if: ${{ env.SECRET_KEY != 0 }}
    steps:
      - uses: actions/checkout@v3

      - id: two
        run: |
          echo "two"

  three:
    runs-on: ubuntu-latest
    needs: [one, two]
    if: always() && ( needs.one.result == 'success' || needs.two.result == 'success' )
    steps:
      - uses: actions/checkout@v3

      - id:   three
        run: |
          echo "  three"
