name: Matrix Test

on:
  push:
    

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "Changes:"
          git diff --name-only HEAD^
          echo ""
          
          echo 'MATRIX<<EOF' >> $GITHUB_ENV
          echo '[' >> $GITHUB_ENV
          echo '{ "server": "quarkus", "tests": "LoginTest" }' >> $GITHUB_ENV
          if ( git diff --name-only HEAD^ | grep  -q '^undertow/' ); then
            echo ', { "server": "undertow", "tests": "LogoutTest" }' >> $GITHUB_ENV
          fi
          echo ']' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
    outputs:
      matrix: ${{ env.MATRIX }}

  echo:
    needs: define-matrix
  
    runs-on: ubuntu-latest

    steps:
    - name: Echo
      run: |
        echo "${{ needs.define-matrix.outputs.matrix }}"

  greet:
    needs: define-matrix
    strategy:
      matrix: 
        include: ${{ fromJson(needs.define-matrix.outputs.matrix) }}          
  
    runs-on: ubuntu-latest

    steps:
    - name: Echo
      run: |
        echo "${{ matrix.server }} ${{ matrix.tests }}"
