name: Info

on:
  workflow_dispatch:

jobs:
  cpu:
    runs-on: ubuntu-latest

    steps:
    - name: lscpu
      run: lscpu

    - name: cpuinfo
      run: cat /proc/cpuinfo
      
    - name: meminfo
      run: cat /proc/meminfo
