name: Reusable workflow

on:
  workflow_call:
    inputs:
      summary:
        description: "Print summary"
        default: false
        type: boolean
        required: false
      version:
        description: "Version to be released"
        default: ""
        type: string
        required: false
    outputs:
      gh-org:
        description: "GitHub Organization"
        value: ${{ jobs.env.outputs.gh-org }}
      mvn-releases-url:
        description: "Maven Releases URL"
        value: ${{ jobs.env.outputs.mvn-releases-url }}
      mvn-snapshots-url:
        description: "Maven Snapshots URL"
        value: ${{ jobs.env.outputs.mvn-snapshots-url }}
      quay-org:
        description: "Quay Organization"
        value: ${{ jobs.env.outputs.quay-org }}

jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      gh-org: ${{ steps.load-env.outputs.gh-org }}
      mvn-url: ${{ steps.load-env.outputs.mvn-releases-url }}
      quay-org: ${{ steps.load-env.outputs.quay-org }}
    steps:
      - uses: actions/checkout@v3
      - id: load-env
        run: |
          cat .github/env/${{ github.repository_owner }} | grep '=' | sed 's/=/::/g' | xargs -I {} echo "::set-output name={}"
      - id: summary
        if: ${{ inputs.summary }}
        run: |
          echo "Version: ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY